name: flutter_opencc
description: flutter_opencc bridges OpenCC (Open Chinese Convert, 開放中文轉換) to your Flutter projects.
version: 0.1.0
author: Weizhong Yang a.k.a zonble <zonble@gmail.com>
homepage: https://github.com/zonble/flutter_opencc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: net.zonble.flutter_opencc
    pluginClass: FlutterOpenccPlugin
