name: flutter_open_chinese_convert
description: flutter_open_chinese_convert bridges OpenCC (Open Chinese Convert, 開放中文轉換) to your Flutter projects.
version: 0.1.0
author: Weizhong Yang a.k.a zonble <zonble@gmail.com>
homepage: https://github.com/zonble/flutter_open_chinese_convert

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    androidPackage: net.zonble.flutter_open_chinese_convert
    pluginClass: FlutterOpenccPlugin
