name: Build
on: [push]

jobs:
  build:
    name: Build APK
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x" # you can use 1.7
          channel: "stable" # optional, default to: 'stable'
      - run: flutter pub get
      - name: Build APK
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd example
          flutter build apk --debug
      - name: Build iOS
        if: startsWith(matrix.os, 'macOS')
        run: |
          cd example
          flutter build ios --debug --no-codesign
